import { AppContextProvider } from '@/context/AppContext'
import { GlobalStyle } from '@/styles/GlobalStyles'
import type { Metadata } from 'next'
import StyledComponentsRegistry from '../../registry'

export const metadata: Metadata = {
  title: 'Multi Step Form',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AppContextProvider>
        <GlobalStyle />
        <body>
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
        </body>
      </AppContextProvider>
    </html>
  )
}
